
FROM java

RUN mkdir /usr/src/sm-project

WORKDIR /usr/src/sm-project

ADD target/sdk-example-benchmark-1.0.5.jar /usr/src/sm-project


ENV RABBIT_MQ_HOST_NAME_KEY_=rabbit
ENV HOBBIT_EXPERIMENT_URI_KEY=exp1
ENV HOBBIT_SESSION_ID_KEY=mySessionId
ENV SYSTEM_URI_KEY= http://project-hobbit.eu/sdk-example-benchmark/sensemark2/system
ENV SYSTEM_PARAMETERS_MODEL_KEY={}


CMD java -cp sdk-example-benchmark-1.0.5.jar  org.hobbit.core.run.ComponentStarter org.hobbit.examples.examplebencmark.system.SystemAdapter
