FROM openjdk:8

MAINTAINER Bushra Nazir

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends net-tools curl

ENV HBASE_VERSION 1.2.6
ENV HBASE_URL http://www.apache.org/dist/hbase/$HBASE_VERSION/hbase-$HBASE_VERSION-bin.tar.gz
ENV INIT_DAEMON_BASE_URI http://identifier/init-daemon # added

RUN set -x \
    && curl -fSL "$HBASE_URL" -o /tmp/hbase.tar.gz \
    && curl -fSL "$HBASE_URL.asc" -o /tmp/hbase.tar.gz.asc \
#    && gpg --verify /tmp/hbase.tar.gz.asc \
    && tar -xvf /tmp/hbase.tar.gz -C /opt/ \
    && rm /tmp/hbase.tar.gz*

RUN ln -s /opt/hbase-$HBASE_VERSION/conf /etc/hbase
RUN mkdir /opt/hbase-$HBASE_VERSION/logs

RUN mkdir /hadoop-data

ENV HBASE_PREFIX=/opt/hbase-$HBASE_VERSION
ENV HBASE_CONF_DIR=/etc/hbase

ENV USER=root
ENV PATH $HBASE_PREFIX/bin/:$PATH

ADD entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

# 5-11
# ENTRYPOINT ["/entrypoint.sh"]
RUN mkdir /hbase-sensemark
ADD /target/hbase-sensemark-benchmark-1.0.4.jar /hbase-sensemark/hbase-sensemark-benchmark-1.0.4.jar
CMD /entrypoint.sh && /hbase-sensemark/hbase-sensemark-benchmark-1.0.4.jar